{
 "title": "FastAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(app_http_request_latency_seconds_count[1m])",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(app_http_request_latency_seconds_count[1m]))",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,status_code)(increase(app_http_request_latency_seconds_count{status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{ uri }} - {{ status_code }}"
    },
    {
     "expr": "sum(increase(app_http_request_latency_seconds_count[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Bytes total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(app_http_response_bytes_total[1m]))",
     "legendFormat": "{{ uri }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_http_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_http_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_http_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_http_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_http_request_latency_seconds_sum{handler!=\"none\"} / app_http_request_latency_seconds_count",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  }
 ]
}